In [2]:
!pip install yfinance pandas

Collecting yfinance
  Downloading yfinance-0.2.65-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.16.5 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from yfinance) (2.3.2)
Requirement already satisfied: requests>=2.31 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from yfinance) (2.32.4)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: platformdirs>=2.0.0 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from yfinance) (2025.2)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.6-py312-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.2.tar.gz (949 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 949.2/949.2 kB 69.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from yfinance) (4.13.4)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.13.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-6.32.0-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: soupsieve>1.2 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.14.0)
Requirement already satisfied: cffi>=1.12.0 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from curl_cffi>=0.7->yfinance) (2025.6.15)
Requirement already satisfied: pycparser in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/gitpod/.pyenv/versions/3.12.11/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.4.0)
Downloading yfinance-0.2.65-py2.py3-none-any.whl (119 kB)
Downloading curl_cffi-0.13.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 113.9 MB/s eta 0:00:00
Downloading frozendict-2.4.6-py312-none-any.whl (16 kB)
Downloading protobuf-6.32.0-cp39-abi3-manylinux2014_x86_64.whl (322 kB)
Downloading websockets-15.0.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (182 kB)
Building wheels for collected packages: multitasking, peewee
  DEPRECATION: Building 'multitasking' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'multitasking'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for multitasking (setup.py) ... done
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15636 sha256=ce43707de89da3e161a011cf171c6160d85e1ff44bea321d50936a181ab7897e
  Stored in directory: /workspace/.pyenv_mirror/pip_cache/wheels/cc/bd/6f/664d62c99327abeef7d86489e6631cbf45b56fbf7ef1d6ef00
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.18.2-cp312-cp312-linux_x86_64.whl size=1020990 sha256=cf65c65eb7afa9a994ddf5ea97122afde4b48a7cec85348918754dfb33df7873
  Stored in directory: /workspace/.pyenv_mirror/pip_cache/wheels/d1/df/a9/0202b051c65b11c992dd6db9f2babdd2c44ec7d35d511be5d3
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, protobuf, frozendict, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [yfinance]6/7 [yfinance]]]
Successfully installed curl_cffi-0.13.0 frozendict-2.4.6 multitasking-0.0.12 peewee-3.18.2 protobuf-6.32.0 websockets-15.0.1 yfinance-0.2.65

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [3]:
import yfinance as yf
import pandas as pd

In [5]:
symbol = 'AAPL'
df = yf.download(symbol, start="2015-01-01", end="2025-08-19")

/tmp/ipykernel_2192/1144155368.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(symbol, start="2015-01-01", end="2025-08-19")
[*********************100%***********************]  1 of 1 completed

In [6]:
df.head(10)

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.261044  24.729267  23.821668  24.718171  212818400
2015-01-05  23.577574  24.110150  23.391173  24.030263  257142000
2015-01-06  23.579794  23.839424  23.218085  23.641928  263188400
2015-01-07  23.910437  24.010294  23.677434  23.788387  160423600
2015-01-08  24.829134  24.886830  24.121251  24.238863  237458000
2015-01-09  24.855759  25.130922  24.456326  25.002216  214798000
2015-01-12  24.243292  24.993335  24.143435  24.986678  198603200
2015-01-13  24.458544  25.031063  24.167847  24.727051  268367600
2015-01-14  24.365339  24.518454  24.076860  24.196690  195826400
2015-01-15  23.704060  24.423036  23.668555  24.409723  240056000

In [7]:
df.info

<bound method DataFrame.info of Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2015-01-02   24.261044   24.729267   23.821668   24.718171  212818400
2015-01-05   23.577574   24.110150   23.391173   24.030263  257142000
2015-01-06   23.579794   23.839424   23.218085   23.641928  263188400
2015-01-07   23.910437   24.010294   23.677434   23.788387  160423600
2015-01-08   24.829134   24.886830   24.121251   24.238863  237458000
...                ...         ...         ...         ...        ...
2025-08-12  229.649994  230.800003  227.070007  228.009995   55626200
2025-08-13  233.330002  235.000000  230.429993  231.070007   69878500
2025-08-14  232.779999  235.119995  230.850006  234.059998   51916300
2025-08-15  231.589996  234.279999  229.339996  234.000000   56038700
2025-08-18  230.889999  233.119995  230.110001  231.699997   37451700

[2672 rows x 5 columns]>

In [8]:
df.describe(include="all")

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   2672.000000  2672.000000  2672.000000  2672.000000  2.672000e+03
mean     101.061157   102.075724    99.944003   100.968045  1.136290e+08
std       69.792061    70.480376    69.018273    69.712657  6.804936e+07
min       20.624050    20.927680    20.425436    20.546430  2.323470e+07
25%       36.265045    36.484779    35.929499    36.260833  6.777740e+07
50%       76.727558    77.299974    75.979730    76.546423  9.650920e+07
75%      162.982140   164.627783   161.648769   162.966115  1.385533e+08
max      258.103729   259.179926   256.718662   257.276679  6.488252e+08

In [9]:
df.shape

(2672, 5)

In [10]:
data.to_csv(f'{symbol}_raw.csv')